function comav200(){var bb='',$=' top: -1000px;',yb='" for "gwt:onLoadErrorFn"',wb='" for "gwt:onPropertyErrorFn"',hb='");',zb='#',pc='.cache.js',Bb='/',Hb='//',oc=':',qb='::',Cc=':moduleBase',ab='<!doctype html>',cb='<html><head><\/head><body><\/body><\/html>',tb='=',Ab='?',vb='Bad handler "',_='CSS1Compat',fb='Chrome',eb='DOMContentLoaded',V='DUMMY',nc="GWT module 'comav200' may need to be (re)compiled",Bc='Ignoring non-whitelisted Dev Mode URL: ',Ac='__gwtDevModeHook:comav200',bc='adobeair',cc='air',Gb='base',Eb='baseUrl',Q='begin',W='body',P='bootstrap',Jb='chrome',Db='clear.cache.gif',T='comav200',mc='comav200.devmode.js',Fb='comav200.nocache.js',pb='comav200::',sb='content',xc='end',gb='eval("',zc='file:',Zb='gecko',_b='gecko1_8',ac='gecko1_9',R='gwt.codesvr.comav200=',S='gwt.codesvr=',vc='gwt/standard/standard.css',xb='gwt:onLoadErrorFn',ub='gwt:onPropertyErrorFn',rb='gwt:property',Ib='gxt.user.agent',mb='head',tc='href',yc='http:',Mb='ie10',Sb='ie6',Qb='ie7',Ob='ie8',Nb='ie9',X='iframe',Cb='img',jb='javascript',Y='javascript:""',qc='link',hc='linux',uc='loadExternalRefs',gc='mac',fc='mac os x',ec='macintosh',nb='meta',lb='moduleRequested',kb='moduleStartup',Lb='msie',Rb='msie 6',Pb='msie 7',ob='name',Kb='opera',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',rc='rel',wc='reset.css',$b='rv:1.8',Tb='safari',Vb='safari3',Xb='safari4',Yb='safari5',ib='script',lc='selectingPermutation',U='startup',sc='stylesheet',db='undefined',kc='unknown',dc='user.agent.os',Ub='version/3',Wb='version/4',jc='win32',ic='windows';var o=window;var p=document;r(P,Q);function q(){var a=o.location.search;return a.indexOf(R)!=-1||a.indexOf(S)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:T,sessionId:o.__gwtStatsSessionId,subSystem:U,evtGroup:a,millis:(new Date).getTime(),type:b})}}
comav200.__sendStats=r;comav200.__moduleName=T;comav200.__errFn=null;comav200.__moduleBase=V;comav200.__softPermutationId=0;comav200.__computePropValue=null;comav200.__getPropMap=null;comav200.__gwtInstallCode=function(){};comav200.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[T]={moduleName:T};var v;function w(){B();return v}
function A(){B();return v.getElementsByTagName(W)[0]}
function B(){if(v){return}var a=p.createElement(X);a.src=Y;a.id=T;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==_?ab:bb;v.write(b+cb);v.close()}
function C(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=w();var g;if(navigator.userAgent.indexOf(fb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(gb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(hb));g=f.createElement(ib);g.language=jb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(ib);g.language=jb;g.text=c[i];e.appendChild(g);d(e,g)}}}
comav200.onScriptDownloaded=function(a){l(function(){m(a)})};r(kb,lb);var n=p.createElement(ib);n.src=k;p.getElementsByTagName(mb)[0].appendChild(n)}
comav200.__startLoadingFragment=function(a){return G(a)};comav200.__installRunAsyncCode=function(a){var b=A();var c=w().createElement(ib);c.language=jb;c.text=a;b.appendChild(c);b.removeChild(c)};function D(){var c={};var d;var e;var f=p.getElementsByTagName(nb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(ob),k;if(j){j=j.replace(pb,bb);if(j.indexOf(qb)>=0){continue}if(j==rb){k=i.getAttribute(sb);if(k){var l,m=k.indexOf(tb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=bb}c[j]=l}}else if(j==ub){k=i.getAttribute(sb);if(k){try{d=eval(k)}catch(a){alert(vb+k+wb)}}}else if(j==xb){k=i.getAttribute(sb);if(k){try{e=eval(k)}catch(a){alert(vb+k+yb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;comav200.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(zb);if(b==-1){b=a.length}var c=a.indexOf(Ab);if(c==-1){c=a.length}var d=a.lastIndexOf(Bb,Math.min(c,b));return d>=0?a.substring(0,d+1):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Cb);b.src=a+Db;a=e(b.src)}return a}
function g(){var a=t(Eb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(ib);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Fb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Gb);if(a.length>0){return a[a.length-1].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Hb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return comav200.__moduleBase+a}
function H(){var f=[];var g;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
i[Ib]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Jb)!=-1)return Jb;if(a.indexOf(Kb)!=-1)return Kb;if(a.indexOf(Lb)!=-1){if(p.documentMode>=10)return Mb;if(p.documentMode>=9)return Nb;if(p.documentMode>=8)return Ob;if(a.indexOf(Pb)!=-1)return Qb;if(a.indexOf(Rb)!=-1)return Sb;return Mb}if(a.indexOf(Tb)!=-1){if(a.indexOf(Ub)!=-1)return Vb;if(a.indexOf(Wb)!=-1)return Xb;return Yb}if(a.indexOf(Zb)!=-1){if(a.indexOf($b)!=-1)return _b;return ac}if(a.indexOf(bc)!=-1)return cc;return null};h[Ib]={air:0,chrome:1,gecko1_8:2,gecko1_9:3,ie10:4,ie8:5,ie9:6,safari3:7,safari4:8,safari5:9};i[dc]=function(){var a=o.navigator.userAgent.toLowerCase();if(a.indexOf(ec)!=-1||a.indexOf(fc)!=-1){return gc}if(a.indexOf(hc)!=-1){return hc}if(a.indexOf(ic)!=-1||a.indexOf(jc)!=-1){return ic}return kc};h[dc]={linux:0,mac:1,unknown:2,windows:3};s=function(a,b){return b in h[a]};comav200.__getPropMap=function(){var a={};for(var b in h){if(h.hasOwnProperty(b)){a[b]=j(b)}}return a};comav200.__computePropValue=j;o.__gwt_activeModules[T].bindings=comav200.__getPropMap;r(P,lc);if(q()){return G(mc)}var k;try{alert(nc);return;var l=k.indexOf(oc);if(l!=-1){g=parseInt(k.substring(l+1),10);k=k.substring(0,l)}}catch(a){}comav200.__softPermutationId=g;return G(k+pc)}
function I(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(qc);b.setAttribute(rc,sc);b.setAttribute(tc,G(a));p.getElementsByTagName(mb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(uc,Q);c(vc);c(wc);r(uc,xc)}
D();comav200.__moduleBase=F();u[T].moduleBase=comav200.__moduleBase;var J=H();if(o){var K=!!(o.location.protocol==yc||o.location.protocol==zc);o.__gwt_activeModules[T].canRedirect=K;if(K){var L=Ac;var M=o.sessionStorage[L];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(M)){if(M&&(window.console&&console.log)){console.log(Bc+M)}M=bb}if(M&&!o[L]){o[L]=true;o[L+Cc]=F();var N=p.createElement(ib);N.src=M;var O=p.getElementsByTagName(mb)[0];O.insertBefore(N,O.firstElementChild||O.children[0]);return false}}}I();r(P,xc);C(J);return true}
comav200.succeeded=comav200();